import type { Product } from './types';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Pure Mustard Oil',
    description: 'Traditional kachi ghani mustard oil, rich in flavor and aroma.',
    longDescription: 'Our Pure Mustard Oil is extracted from the finest quality mustard seeds using the traditional kachi ghani process. This method ensures that the natural properties, antioxidants, and essential oils are retained. It has a pungent aroma and a rich, nutty flavor, perfect for traditional Indian cooking, pickles, and marinades. Rich in MUFA, PUFA, Omega-3 & Omega-6 fatty acids.',
    price: 180,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'mustard oil bottle',
    category: 'Mustard Oil',
    dietaryTags: ['Cold-Pressed', 'Unrefined'],
    origin: 'India',
    size: '1L',
    stock: 100,
    attributes: [{ key: 'Extraction', value: 'Kachi Ghani (Cold-Pressed)' }, { key: 'Best For', value: 'Pickling, Deep Frying, Sautéing' }],
    sku: 'LRKR-MO-1L',
  },
  {
    id: '2',
    name: 'Organic Sesame Oil',
    description: 'Cold-pressed organic sesame oil, ideal for Asian cuisine and massages.',
    longDescription: 'Experience the nutty and delicate flavor of our Organic Sesame Oil. Cold-pressed from certified organic sesame seeds, this oil is rich in antioxidants and healthy fats. It is a staple in many Asian cuisines for stir-frying and seasoning, and is also highly valued in Ayurveda for its therapeutic properties when used for massage.',
    price: 350,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'sesame oil bottle',
    category: 'Sesame Oil',
    dietaryTags: ['Organic', 'Cold-Pressed', 'Gluten-Free'],
    origin: 'India',
    size: '500ml',
    stock: 75,
    attributes: [{ key: 'Extraction', value: 'Cold-Pressed' }, { key: 'Flavor Profile', value: 'Nutty, Delicate' }],
    sku: 'LRKR-SO-500ML',
  },
  {
    id: '3',
    name: 'Extra Virgin Olive Oil',
    description: 'Premium quality extra virgin olive oil, perfect for salads and dressings.',
    longDescription: 'Imported from the finest groves, our Extra Virgin Olive Oil is cold-extracted to preserve its fruity aroma, rich flavor, and high polyphenol content. Ideal for drizzling over salads, pastas, and breads, or for use in light cooking. A cornerstone of the Mediterranean diet, known for its health benefits.',
    price: 750,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'olive oil bottle',
    category: 'Olive Oil',
    dietaryTags: ['Extra Virgin', 'Cold-Pressed', 'Non-GMO'],
    origin: 'Spain',
    size: '750ml',
    stock: 50,
    attributes: [{ key: 'Acidity', value: '< 0.8%' }, { key: 'Flavor Profile', value: 'Fruity, Peppery' }],
    sku: 'LRKR-EVOO-750ML',
  },
  {
    id: '4',
    name: 'Virgin Coconut Oil',
    description: 'Cold-pressed virgin coconut oil, excellent for cooking and skincare.',
    longDescription: 'Our Virgin Coconut Oil is made from fresh, high-quality coconuts using a cold-press method that retains its natural lauric acid content, aroma, and flavor. This versatile oil can be used for medium-heat cooking, baking, or as a healthy spread. It is also renowned for its benefits in hair and skin care.',
    price: 420,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'coconut oil jar',
    category: 'Coconut Oil',
    dietaryTags: ['Organic', 'Virgin', 'Cold-Pressed'],
    origin: 'India',
    size: '500ml',
    stock: 80,
    attributes: [{ key: 'Extraction', value: 'Cold-Pressed' }, { key: 'Aroma', value: 'Fresh Coconut' }],
    sku: 'LRKR-VCO-500ML',
  },
  {
    id: '5',
    name: 'Refined Groundnut Oil',
    description: 'Light and neutral-flavored groundnut oil, suitable for all types of cooking.',
    longDescription: 'Our Refined Groundnut Oil is a versatile cooking oil with a high smoke point, making it ideal for frying, sautéing, and general cooking. It has a light, neutral flavor that doesn\'t overpower your dishes. Processed to ensure purity and stability.',
    price: 220,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'groundnut oil bottle',
    category: 'Groundnut Oil',
    dietaryTags: ['Refined'],
    origin: 'India',
    size: '1L',
    stock: 120,
    attributes: [{ key: 'Smoke Point', value: 'High' }, { key: 'Flavor Profile', value: 'Neutral' }],
    sku: 'LRKR-GO-1L',
  },
  {
    id: '6',
    name: 'Cold-Pressed Sunflower Oil',
    description: 'Nutrient-rich cold-pressed sunflower oil, good for heart health.',
    longDescription: 'Extracted from high-oleic sunflower seeds, our Cold-Pressed Sunflower Oil is rich in Vitamin E and monounsaturated fats. It has a mild flavor and a high smoke point, making it suitable for various cooking methods including frying and baking. A healthy choice for your everyday cooking needs.',
    price: 280,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'sunflower oil bottle',
    category: 'Sunflower Oil',
    dietaryTags: ['Cold-Pressed', 'High-Oleic'],
    origin: 'India',
    size: '1L',
    stock: 90,
    attributes: [{ key: 'Rich In', value: 'Vitamin E, MUFA' }, { key: 'Flavor Profile', value: 'Mild' }],
    sku: 'LRKR-SFO-CP-1L',
  },
];

export const FEATURED_PRODUCTS_IDS = ['1', '3', '4'];
